language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
  - nightly

sudo: false

matrix:
  allow_failures:
    - python: nightly

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - make test
  - make coverage

after_success:
  coveralls
